language: node_js
services: 
  - mysql
dist: bionic
node_js:
  - 10
  - 12
cache:
  directories:
    - node_modules

before_install:
  - cp .deploy/database.config.json config/database.config.json
  
install:
  - npm install
  - npm install -g codecov

script:
  - npm run test

after_success:
  - if [[ $TRAVIS_NODE_VERSION == 10 ]]; then codecov; fi
