language: node_js

services: 
  - mysql
  - docker

dist: bionic

node_js:
  - 10
  - 12

cache:
  directories:
    - node_modules

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [[ $TRAVIS_NODE_VERSION == 10 ]]; then docker build -t ahugues/porygon-backend .; fi
  - cp .deploy/database.config.json config/database.config.json
  
install:
  - npm install
  - npm install -g codecov
  - npm install -g db-migrate

script:
  - mysql -u travis -e 'CREATE DATABASE porygonTest'
  - db-migrate db:create --config config/database.config.json --env test porygonTest
  - db-migrate --config config/database.config.json --env test up
  - npm run test

after_success:
  - if [[ $TRAVIS_NODE_VERSION == 10 ]]; then codecov; fi

deploy:
  - provider: script
    script: bash docker_push
    on:
      node: 10
      branch: master
  - provider: script
    script: bash docker_push
    on:
      node: 10
      all_branches: true
      tag: true
